### ISSUE TITLE
Código Fonte Jekyll para contribuição

### ISSUE THREAD

**Issue by fabioars** [willianmano/reactdocs-pt_br#3]
Opa Mano, 

Tu poderia fazer uma branch orphan com o código fonte pra gente poder contribuir. (::

**Comment by willianmano** [comment]
@1fabiosoares Seria uma boa... falta o tempo... não quer tocar esse projeto? Te dou permissões no repo. :)

**Comment by fabioars** [comment]
Opa, posso tocar sim.

**Comment by willianmano** [comment]
Pronto. =)
